In [ ]:
#given an image, identify the type of visualization

In [3]:
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers, models, Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout
from PIL import Image, ImageOps
import pprint
import os

In [4]:
def load_data(directories,X):
    count = 0
    for directory in directories:
        for filename in os.listdir(directory):
            f = os.path.join(directory, filename)
            if os.path.isfile(f):
                training_image = Image.open(f)
                training_image = training_image.resize((300,300)) 
                for i in range(300):
                    for j in range(300):
                        pixel = training_image.getpixel((i, j))
                        #print(pixel)
                        pixel_new = (pixel[0])
                        if pixel_new == 255 or pixel_new == 255.0:
                            pixel_new = 0
                        X[count][i][j] = pixel_new 
                       # print(pixel_new)
                count+=1
    return X
           # training_image.show()

In [13]:
X = np.zeros((107,300,300)) 
directories = [r"C:\Users\local1\sarvghad visualizations\CNN_1bar",
               r"C:\Users\local1\sarvghad visualizations\CNN_2bar",
               r"C:\Users\local1\sarvghad visualizations\CNN_1line",
               r"C:\Users\local1\sarvghad visualizations\CNN_2line"
              ]
X = load_data(directories,X)
y = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,#1bar
     0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,#2bar
     1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,#1line
     1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1#2line
    ]
y=np.array(y)

In [6]:
#pprint.pprint(X[0][0])
X.size
#print(len(X[0][150]))

9630000

In [14]:
X = tf.expand_dims(X, axis=-1)

In [15]:
model = Sequential([
    Conv2D(filters=32,kernel_size=(3,3), activation='relu',name="convLayer1"),
    MaxPooling2D(pool_size=(2,2)),

    Conv2D(filters=32,kernel_size=(3,3), activation='relu',name="convLayer2"),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.15),

    Conv2D(filters=64,kernel_size=(3,3), activation='relu',name="convLayer3"),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.15),

    Flatten(),
    Dense(128, activation='relu',name="relu1"),
    Dropout(0.15),
    Dense(64, activation='relu',name="relu2"),
    Dropout(0.15),
    Dense(32, activation='relu',name="relu3"),
    Dropout(0.15),
    Dense(2, activation='softmax',name="softmax1")
])

In [17]:
model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy'],
              optimizer=tf.keras.optimizers.Adam(0.001),
             )

In [18]:
model.fit(X,y,epochs=10)

Epoch 1/10
4/4 [==============================] - 9s 1s/step - loss: 61.9330 - accuracy: 0.5047
Epoch 2/10
4/4 [==============================] - 7s 2s/step - loss: 15.7464 - accuracy: 0.5794
Epoch 3/10
4/4 [==============================] - 6s 2s/step - loss: 6.1310 - accuracy: 0.6729
Epoch 4/10
4/4 [==============================] - 7s 2s/step - loss: 0.8985 - accuracy: 0.8224
Epoch 5/10
4/4 [==============================] - 7s 2s/step - loss: 0.4580 - accuracy: 0.8224
Epoch 6/10
4/4 [==============================] - 6s 2s/step - loss: 0.2025 - accuracy: 0.9252
Epoch 7/10
4/4 [==============================] - 7s 2s/step - loss: 0.1830 - accuracy: 0.9439
Epoch 8/10
4/4 [==============================] - 6s 2s/step - loss: 0.1429 - accuracy: 0.9720
Epoch 9/10
4/4 [==============================] - 6s 2s/step - loss: 0.0717 - accuracy: 0.9720
Epoch 10/10
4/4 [==============================] - 6s 2s/step - loss: 0.0775 - accuracy: 0.9720


In [19]:
X_test = np.zeros((8,300,300)) 
test_directories = [
                    r"C:\Users\local1\sarvghad visualizations\Evaluation Graphs\COVID-19\2Line"
                 ]
load_data(test_directories,X_test)

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [20]:
a= model.predict(X_test)
print(a)
predictions = {}
for i in range(len(a)):
    x = (str(a[i]).split())
    for j in x:
        if "]" in j:
            x[(x.index(j))] = j.replace("]","")
        if "[" in j:
            x[(x.index(j))] = j.replace("[","")
    for j in x:
        if j == "":
            x.remove(j)
        else:
            x[(x.index(j))] = float(j)
    index = (x.index(max(x)))
    if index == 0:
        print("bar",max(x))
        predictions[i] = "bar"
    if index == 1:
        print("line",max(x))
        predictions[i] = "line"

1/1 [==============================] - 0s 404ms/step
[[0.2655981  0.7344019 ]
 [0.03672815 0.9632719 ]
 [0.11583641 0.88416356]
 [0.241885   0.75811493]
 [0.19501273 0.80498725]
 [0.31903905 0.680961  ]
 [0.36493325 0.63506675]
 [0.3815794  0.6184206 ]]
line 0.7344019
line 0.9632719
line 0.88416356
line 0.75811493
line 0.80498725
line 0.680961
line 0.63506675
line 0.6184206


In [ ]:
#2line detection model
X = np.zeros((49,300,300)) 
directories = [
               r"C:\Users\local1\sarvghad visualizations\CNN_1line",
               r"C:\Users\local1\sarvghad visualizations\CNN_2line"
              ]
X = load_data(directories,X)
y = [
     1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,#1line
     0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0#2line
    ]
y=np.array(y)
X = tf.expand_dims(X, axis=-1)
model1 = Sequential([
    Conv2D(filters=32,kernel_size=(3,3), activation='relu',name="convLayer1"),
    MaxPooling2D(pool_size=(2,2)),

    Conv2D(filters=32,kernel_size=(3,3), activation='relu',name="convLayer2"),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.15),

    Conv2D(filters=64,kernel_size=(3,3), activation='relu',name="convLayer3"),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.15),

    Flatten(),
    Dense(128, activation='relu',name="relu1"),
    Dropout(0.15),
    Dense(64, activation='relu',name="relu2"),
    Dropout(0.15),
    Dense(32, activation='relu',name="relu3"),
    Dropout(0.15),
    Dense(2, activation='softmax',name="softmax1")
])
model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy'],
              optimizer=tf.keras.optimizers.Adam(0.001),
             )
model.fit(X,y,epochs=10)

In [ ]:
#2bar detection model
X = np.zeros((58,300,300)) 
directories = [r"C:\Users\local1\sarvghad visualizations\CNN_1bar",
               r"C:\Users\local1\sarvghad visualizations\CNN_2bar",
              ]
X = load_data(directories,X)
y = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,#1bar
     0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0#2bar
    ]
y=np.array(y)
X = tf.expand_dims(X, axis=-1)
model2 = Sequential([
    Conv2D(filters=32,kernel_size=(3,3), activation='relu',name="convLayer1"),
    MaxPooling2D(pool_size=(2,2)),

    Conv2D(filters=32,kernel_size=(3,3), activation='relu',name="convLayer2"),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.15),

    Conv2D(filters=64,kernel_size=(3,3), activation='relu',name="convLayer3"),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.15),

    Flatten(),
    Dense(128, activation='relu',name="relu1"),
    Dropout(0.15),
    Dense(64, activation='relu',name="relu2"),
    Dropout(0.15),
    Dense(32, activation='relu',name="relu3"),
    Dropout(0.15),
    Dense(2, activation='softmax',name="softmax1")
])
model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy'],
              optimizer=tf.keras.optimizers.Adam(0.001),
             )
model.fit(X,y,epochs=10)

In [24]:
print(X_test[7])
pprint.pprint(predictions)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
{0: 'line',
 1: 'line',
 2: 'line',
 3: 'line',
 4: 'line',
 5: 'line',
 6: 'line',
 7: 'line'}


In [17]:
pprint.pprint(predictions)
for key in predictions:
    if predictions[key] == "bar":
        model2.predict(X_test[key])
    else if predictions[key] == "line":
        model1.predict(X_test[key])

{0: 'bar',
 1: 'line',
 2: 'line',
 3: 'line',
 4: 'line',
 5: 'bar',
 6: 'bar',
 7: 'line'}
