In [1]:
#given an image, identify the type of visualization

In [27]:
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers, models, Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout
from PIL import Image, ImageOps
import os

In [28]:
def load_data(directories,X):
    count = 0
    for directory in directories:
        for filename in os.listdir(directory):
            f = os.path.join(directory, filename)
            if os.path.isfile(f):
                training_image = Image.open(f)
                training_image = training_image.resize((300,300)) 
                for i in range(300):
                    for j in range(300):
                        pixel = training_image.getpixel((i, j))
                        pixel_new = (pixel[0]/255.0)
                        X[count][i][j] = pixel_new
                count+=1
           # training_image.show()

In [29]:
X = np.zeros((52,300,300)) 
directories = [r"C:\Users\local1\sarvghad visualizations\CNN_1bar",
               r"C:\Users\local1\sarvghad visualizations\CNN_2bar",
               r"C:\Users\local1\sarvghad visualizations\CNN_1line",
               r"C:\Users\local1\sarvghad visualizations\CNN_2line"
              ]
load_data(directories,X)
y = [0,0,0,0,0,0,0,0,0,0,0,0,0,
     1,1,1,1,1,1,1,1,1,1,1,1,1,
     2,2,2,2,2,2,2,2,2,2,2,2,2,
     3,3,3,3,3,3,3,3,3,3,3,3,3
    ]
y=np.array(y)

In [30]:
X = tf.expand_dims(X, axis=-1)

In [31]:
model = Sequential([
    Conv2D(filters=32,kernel_size=(3,3), activation='relu',name="convLayer1"),
    MaxPooling2D(pool_size=(2,2)),

    Conv2D(filters=32,kernel_size=(3,3), activation='relu',name="convLayer2"),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.15),

    Conv2D(filters=64,kernel_size=(3,3), activation='relu',name="convLayer3"),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.15),

    Flatten(),
    Dense(128, activation='relu',name="relu1"),
    Dropout(0.15),
    Dense(64, activation='relu',name="relu2"),
    Dropout(0.15),
    Dense(32, activation='relu',name="relu3"),
    Dropout(0.15),
    Dense(4, activation='softmax',name="softmax1")
])

In [32]:
model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy'],
              optimizer=tf.keras.optimizers.Adam(0.001),
             )

In [33]:
model.fit(X,y,epochs=30)

Epoch 1/30
2/2 [==============================] - 8s 2s/step - loss: 1.9112 - accuracy: 0.1731
Epoch 2/30
2/2 [==============================] - 4s 2s/step - loss: 1.6931 - accuracy: 0.2692
Epoch 3/30
2/2 [==============================] - 4s 2s/step - loss: 1.3684 - accuracy: 0.3269
Epoch 4/30
2/2 [==============================] - 4s 2s/step - loss: 1.3930 - accuracy: 0.2692
Epoch 5/30
2/2 [==============================] - 4s 2s/step - loss: 1.3759 - accuracy: 0.3654
Epoch 6/30
2/2 [==============================] - 4s 2s/step - loss: 1.3734 - accuracy: 0.3846
Epoch 7/30
2/2 [==============================] - 4s 2s/step - loss: 1.3219 - accuracy: 0.6154
Epoch 8/30
2/2 [==============================] - 5s 2s/step - loss: 1.2916 - accuracy: 0.5000
Epoch 9/30
2/2 [==============================] - 5s 2s/step - loss: 1.2210 - accuracy: 0.5962
Epoch 10/30
2/2 [==============================] - 5s 2s/step - loss: 1.1469 - accuracy: 0.6346
Epoch 11/30
2/2 [==============================] 

In [34]:
X_test = np.zeros((16,300,300)) 
test_directories = [r"C:\Users\local1\sarvghad visualizations\Test_CNN_1bar",
                    r"C:\Users\local1\sarvghad visualizations\Test_CNN_2bar",
                    r"C:\Users\local1\sarvghad visualizations\Test_CNN_1line",
                    r"C:\Users\local1\sarvghad visualizations\Test_CNN_2line"
                 ]
load_data(test_directories,X_test)

In [35]:
a= model.predict(X_test)
print(a)

1/1 [==============================] - 1s 555ms/step
[[9.9925953e-01 4.1932941e-05 6.6194794e-04 3.6558969e-05]
 [8.8080627e-01 2.5594451e-03 1.1402284e-01 2.6113472e-03]
 [9.9898773e-01 4.6512832e-05 9.1903046e-04 4.6706191e-05]
 [9.9992657e-01 3.8631401e-06 6.5531203e-05 3.9633414e-06]
 [1.0314469e-03 9.8889625e-01 1.8271575e-03 8.2451841e-03]
 [9.6557769e-06 9.9977916e-01 2.5180207e-05 1.8602620e-04]
 [3.6766851e-06 9.9988484e-01 1.3742746e-05 9.7742035e-05]
 [1.9590330e-05 9.9972790e-01 4.3369928e-05 2.0910846e-04]
 [2.5144021e-04 1.8308304e-04 9.9887437e-01 6.9103483e-04]
 [3.1670951e-03 9.2115789e-04 9.9432373e-01 1.5881044e-03]
 [4.5777514e-04 3.0680301e-04 9.9825650e-01 9.7883213e-04]
 [4.1828435e-04 2.9183764e-04 9.9830461e-01 9.8519912e-04]
 [4.5024715e-03 1.4533824e-02 4.7248043e-03 9.7623891e-01]
 [4.8168533e-04 3.1088628e-03 2.2228605e-04 9.9618715e-01]
 [6.4818007e-03 1.1483411e-02 2.4907198e-03 9.7954398e-01]
 [3.8413696e-03 8.6365156e-03 1.5368981e-03 9.8598528e-01]]
